---
- name: password shadow | Ensure minimum days between password changes is configured
  lineinfile:
    dest: /etc/login.defs
    state: present
    regexp: "^PASS_MIN_DAYS"
    line: "PASS_MIN_DAYS {{ shadow_pass_min_days }}"
  tags: ["hardening:passwordshadow"]

- name: password shadow | Ensure password expiration is 365 days or less
  lineinfile:
    dest: /etc/login.defs
    state: present
    regexp: "^PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS {{ shadow_pass_max_days }}"
  tags: ["hardening:passwordshadow"]

- name: password shadow | Ensure password warning days is 7 or more
  lineinfile:
    dest: /etc/login.defs
    state: present
    regexp: "^PASS_WARN_AGE"
    line: "PASS_WARN_AGE {{ shadow_pass_warn_age }}"
  tags: ["hardening:passwordshadow"]
